export const SYMBOLS = {
  // Use cases
  CreateSubmission: Symbol.for('CreateSubmission'),
  GetSubmission: Symbol.for('GetSubmission'),
  GetSubmissions: Symbol.for('GetSubmissions'),
  UpdateSubmission: Symbol.for('UpdateSubmission'),
  DeleteSubmission: Symbol.for('DeleteSubmission'),
  CreateDecision: Symbol.for('CreateDecision'),
  GetDecision: Symbol.for('GetDecision'),
  GetDecisions: Symbol.for('GetDecisions'),
  UpdateDecision: Symbol.for('UpdateDecision'),
  DeleteDecision: Symbol.for('DeleteDecision'),
  CreateFeedback: Symbol.for('CreateFeedback'),
  GetFeedback: Symbol.for('GetFeedback'),
  GetFeedbacks: Symbol.for('GetFeedbacks'),
  UpdateFeedback: Symbol.for('UpdateFeedback'),
  DeleteFeedback: Symbol.for('DeleteFeedback'),
  SubmitRevision: Symbol.for('SubmitRevision'),
  GetRevision: Symbol.for('GetRevision'),
  GetRevisions: Symbol.for('GetRevisions'),
  GetActiveRevision: Symbol.for('GetActiveRevision'),
  UpdateRevision: Symbol.for('UpdateRevision'),
  DeleteRevision: Symbol.for('DeleteRevision'),
  CreateJournal: Symbol.for('CreateJournal'),
  GetJournal: Symbol.for('GetJournal'),
  GetJournals: Symbol.for('GetJournals'),
  UpdateJournal: Symbol.for('UpdateJournal'),
  DeleteJournal: Symbol.for('DeleteJournal'),
  CreateIssue: Symbol.for('CreateIssue'),
  GetIssue: Symbol.for('GetIssue'),
  GetIssues: Symbol.for('GetIssues'),
  UpdateIssue: Symbol.for('UpdateIssue'),
  DeleteIssue: Symbol.for('DeleteIssue'),
  CreatePublication: Symbol.for('CreatePublication'),
  GetPublication: Symbol.for('GetPublication'),
  GetPublications: Symbol.for('GetPublications'),
  UpdatePublication: Symbol.for('UpdatePublication'),
  DeletePublication: Symbol.for('DeletePublication'),
  CreateParticipant: Symbol.for('CreateParticipant'),
  GetParticipant: Symbol.for('GetParticipant'),
  GetParticipants: Symbol.for('GetParticipants'),
  UpdateParticipant: Symbol.for('UpdateParticipant'),
  DeleteParticipant: Symbol.for('DeleteParticipant'),
  GetUser: Symbol.for('GetUser'),
  GetUsers: Symbol.for('GetUsers'),
  CreateUser: Symbol.for('CreateUser'),
  UpdateUser: Symbol.for('UpdateUser'),
  DeleteUser: Symbol.for('DeleteUser'),
  Login: Symbol.for('Login'),
  Logout: Symbol.for('Logout'),
  GetSession: Symbol.for('GetSession'),
  UpdateSession: Symbol.for('UpdateSession'),
  GetSidebarExtendedState: Symbol.for('GetSidebarExtendedState'),
  SetSidebarExtendedState: Symbol.for('SetSidebarExtendedState'),

  // Repositories
  AuthRepository: Symbol.for('AuthRepository'),
  InternalRepository: Symbol.for('InternalRepository'),
  SubmissionRepository: Symbol.for('SubmissionRepository'),
  RevisionRepository: Symbol.for('RevisionRepository'),
  DecisionRepository: Symbol.for('DecisionRepository'),
  FeedbackRepository: Symbol.for('FeedbackRepository'),
  JournalRepository: Symbol.for('JournalRepository'),
  IssueRepository: Symbol.for('IssueRepository'),
  PublicationRepository: Symbol.for('PublicationRepository'),
  UserRepository: Symbol.for('UserRepository'),
  ParticipantRepository: Symbol.for('ParticipantRepository'),

  // Controllers
  AuthController: Symbol.for('AuthController'),

  // Data sources
  LocalStorageDataSource: Symbol.for('LocalStorageDataSource'),
  SessionStorageDataSource: Symbol.for('SessionStorageDataSource'),
  AuthDataSource: Symbol.for('AuthDataSource'),
  JournalSystemDataSource: Symbol.for('JournalSystemDataSource'),
};
